/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ServerRouteImport } from './routes/server'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LogsConfigIdRouteImport } from './routes/logs.$configId'
import { Route as ApiPublicCronMonitorRouteImport } from './routes/api/public/cron/monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsConfigIdRoute = LogsConfigIdRouteImport.update({
  id: '/logs/$configId',
  path: '/logs/$configId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMonitorRoute = ApiPublicCronMonitorRouteImport.update({
  id: '/api/public/cron/monitor',
  path: '/api/public/cron/monitor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/monitoring': typeof MonitoringRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/logs/$configId': typeof LogsConfigIdRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/monitoring': typeof MonitoringRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/logs/$configId': typeof LogsConfigIdRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/monitoring': typeof MonitoringRoute
  '/server': typeof ServerRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/logs/$configId': typeof LogsConfigIdRoute
  '/api/public/cron/monitor': typeof ApiPublicCronMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/monitoring'
    | '/server'
    | '/settings'
    | '/users'
    | '/logs/$configId'
    | '/api/public/cron/monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/monitoring'
    | '/server'
    | '/settings'
    | '/users'
    | '/logs/$configId'
    | '/api/public/cron/monitor'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/monitoring'
    | '/server'
    | '/settings'
    | '/users'
    | '/logs/$configId'
    | '/api/public/cron/monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  MonitoringRoute: typeof MonitoringRoute
  ServerRoute: typeof ServerRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  LogsConfigIdRoute: typeof LogsConfigIdRoute
  ApiPublicCronMonitorRoute: typeof ApiPublicCronMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$configId': {
      id: '/logs/$configId'
      path: '/logs/$configId'
      fullPath: '/logs/$configId'
      preLoaderRoute: typeof LogsConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monitor': {
      id: '/api/public/cron/monitor'
      path: '/api/public/cron/monitor'
      fullPath: '/api/public/cron/monitor'
      preLoaderRoute: typeof ApiPublicCronMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  MonitoringRoute: MonitoringRoute,
  ServerRoute: ServerRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  LogsConfigIdRoute: LogsConfigIdRoute,
  ApiPublicCronMonitorRoute: ApiPublicCronMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
